random_state: 42
test_size: 0.2
model:
  name: RandomForestClassifier
  params:
    n_estimators: 300
    max_depth: 5
    min_samples_split: 2
    min_samples_leaf: 1
    n_jobs: -1
    random_state: 42
paths:
  data: data/processed
  model: models
  metrics: metrics
  params: params
  plots: plots