random_state: 42
test_size: 0.2
stratify: True
model:
  name: RandomForestClassifier
  params:
    bootstrap: True
    class_weight: 'balanced_subsample'
    criterion: 'log_loss'
    max_depth: 150
    max_features: 'sqrt'
    n_estimators: 1500
    n_jobs: -1
    random_state: 42
paths:
  exported_model_dir: artifacts/model
  plots: artifacts/plots
  metrics: artifacts/metrics 
  params: artifacts/params
  results: artifacts/results


